"""Synthetic batch generation.

Builds the 120-invoice test set: Indian business names, realistic amount
distribution (a few lakh-scale invoices atop a long tail), overdue ages from
freshly-late to written-off-in-spirit. Seeded end to end — the batch that
produced the published metrics can be regenerated byte-for-byte, and every
experiment arm starts from the very same portfolio and the very same debtors.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import date, timedelta

from urudhi.ledger.models import Channel, Debtor, Invoice
from urudhi.ledger.money import rupees
from urudhi.sim.personas import Archetype, Persona, assign_archetypes

_BUSINESS_NAMES = [
    "Kumar Textiles", "Sri Lakshmi Traders", "Annapoorna Foods", "Chennai Fasteners",
    "Coimbatore Pumps & Motors", "Madurai Agro Supplies", "Salem Steel Syndicate",
    "Erode Dyeing Works", "Tirupur Knitwear Co", "Karur Home Fabrics",
    "Nagercoil Spices", "Trichy Auto Components", "Vellore Leather Exports",
    "Thanjavur Rice Mills", "Hosur Tools & Dies", "Pollachi Coir Products",
    "Sivakasi Print House", "Dindigul Locks Ltd", "Namakkal Transport Co",
    "Kanchipuram Silks", "Bengaluru Electricals", "Mysuru Packaging",
    "Hyderabad Pharma Distributors", "Vijayawada Cements", "Kochi Marine Supplies",
    "Rajkot Castings", "Surat Textile Hub", "Ludhiana Cycle Parts",
    "Jaipur Handicrafts Export", "Indore Plastics",
]

_FIRST_NAMES = [
    "Kumar", "Lakshmi", "Ravi", "Priya", "Suresh", "Meena", "Karthik", "Divya",
    "Rajesh", "Anitha", "Vijay", "Sangeetha", "Mohan", "Revathi", "Arun",
]


@dataclass
class SimCase:
    debtor: Debtor
    invoice: Invoice
    archetype: Archetype
    seed: int

    def persona(self) -> Persona:
        """A fresh persona with identical traits — one per experiment arm."""
        return Persona(self.archetype, self.invoice.amount, random.Random(self.seed),
                       language=self.debtor.language)


def generate_batch(
    count: int = 120,
    today: date = date(2026, 8, 24),
    seed: int = 2026,
) -> list[SimCase]:
    rng = random.Random(seed)
    archetypes = assign_archetypes(count, rng)
    cases: list[SimCase] = []
    for i, archetype in enumerate(archetypes, start=1):
        name = f"{_BUSINESS_NAMES[(i - 1) % len(_BUSINESS_NAMES)]}"
        if i > len(_BUSINESS_NAMES):
            name = f"{name} Unit {1 + (i - 1) // len(_BUSINESS_NAMES)}"
        contact = rng.choice(_FIRST_NAMES)

        # Amounts: log-uniform ₹2,000 .. ₹8,00,000 — a long tail with real teeth.
        amount = rupees(int(2_000 * (400 ** rng.random())) // 100 * 100)
        overdue_days = rng.randint(8, 170)
        due_on = today - timedelta(days=overdue_days)

        debtor = Debtor(
            id=f"deb_{i:03d}", name=name, contact_name=contact,
            phone=f"+9198{rng.randint(10_000_000, 99_999_999)}",
            email=f"accounts@{name.lower().replace(' ', '').replace('&', '')[:20]}.example.in",
            preferred_channel=Channel.EMAIL,
            language=rng.choice(["ta", "ta", "hi", "en", "en"]),
        )
        invoice = Invoice(
            id=f"inv_{i:03d}", debtor_id=debtor.id,
            number=f"URU/2026/{i:04d}", amount=amount,
            issued_on=due_on - timedelta(days=30), due_on=due_on,
        )
        cases.append(SimCase(debtor=debtor, invoice=invoice, archetype=archetype,
                             seed=seed * 1_000 + i))
    return cases


def archetype_of(cases: list[SimCase], invoice_id: str) -> Archetype:
    for case in cases:
        if case.invoice.id == invoice_id:
            return case.archetype
    raise KeyError(invoice_id)
